EESchema Schematic File Version 4
LIBS:power
LIBS:device
LIBS:Connector
LIBS:Connector_Generic
LIBS:RF_Module
LIBS:Switch
EELAYER 29 0
EELAYER END
$Descr A4 11693 8268
Sheet 1 1
Title "Pingpang SmartGear ESP32-S3 Control + 1S Power"
Date "2026-08-28"
Rev "v0.2"
Comp "Pingpang SmartGear"
Comment1 "Connectorized field wiring; 1S battery, USB-C, M6 carrier and UI daughter"
Comment2 "Schematic contract for the generated KiCad PCB first article"
Comment3 "Power/current and final component SKUs require bench validation"
Comment4 "Mechanical source: hardware/cad/net_stand.scad"
$EndDescr
$Comp
L RF_Module:ESP32-S3-WROOM-1 U1
U 1 1 1
P 5050 3600
F 0 "U1" H 5050 5381 50  0000 C CNN
F 1 "ESP32-S3-WROOM-1-N16R8" H 5050 5290 50 0000 C CNN
F 2 "RF_Module:ESP32-S3-WROOM-1" H 5050 2100 50 0001 C CNN
F 3 "" H 4700 2150 50 0001 C CNN
	1    5050 3600
	1    0    0    -1
$EndComp
$Comp
L Connector:USB_C_Receptacle_USB2.0_16P J1
U 1 1 2
P 1700 2050
F 0 "J1" H 1807 2917 50 0000 C CNN
F 1 "USB-C POWER + DATA" H 1807 2826 50 0000 C CNN
F 2 "Connector_USB:USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal" H 1850 2050 50 0001 C CNN
F 3 "" H 1850 2050 50 0001 C CNN
	1    1700 2050
	1    0    0    -1
$EndComp
$Comp
L Device:Battery BT1
U 1 1 3
P 1850 4750
F 0 "BT1" H 1958 4796 50 0000 L CNN
F 1 "PROTECTED 1S Li-ion 65x30x7" H 1958 4705 50 0000 L CNN
F 2 "Connector_JST:JST_GH_SM02B-GHS-TB_1x02-1MP_P1.25mm_Horizontal" V 1850 4810 50 0001 C CNN
F 3 "" V 1850 4810 50 0001 C CNN
	1    1850 4750
	1    0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x02 J2
U 1 1 11
P 2900 4750
F 0 "J2" H 2980 4742 50 0000 L CNN
F 1 "BATTERY MX1.25 LOCK 2P" H 2980 4651 50 0000 L CNN
F 2 "Connector_JST:JST_GH_SM02B-GHS-TB_1x02-1MP_P1.25mm_Horizontal" H 2900 4750 50 0001 C CNN
F 3 "" H 2900 4750 50 0001 C CNN
	1    2900 4750
	1    0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x02 J3
U 1 1 12
P 8200 2100
F 0 "J3" H 8280 2092 50 0000 L CNN
F 1 "M6 SENSOR 10-30V MX1.25 2P" H 8280 2001 50 0000 L CNN
F 2 "Connector_JST:JST_GH_SM02B-GHS-TB_1x02-1MP_P1.25mm_Horizontal" H 8200 2100 50 0001 C CNN
F 3 "" H 8200 2100 50 0001 C CNN
	1    8200 2100
	1    0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x02 J6
U 1 1 13
P 8200 6900
F 0 "J6" H 8280 6892 50 0000 L CNN
F 1 "PVDF COMPARATOR AUX MX1.25 2P DNP" H 8280 6801 50 0000 L CNN
F 2 "Connector_JST:JST_GH_SM02B-GHS-TB_1x02-1MP_P1.25mm_Horizontal" H 8200 6900 50 0001 C CNN
F 3 "" H 8200 6900 50 0001 C CNN
	1    8200 6900
	1    0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x09 U2
U 1 1 4
P 3200 4650
F 0 "U2" H 3118 5267 50 0000 C CNN
F 1 "IP5305T-HSOP8-1EP / 1S POWER" H 3118 5176 50 0000 C CNN
	1    3200 4650
	-1   0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x09 U3
U 1 1 5
P 5050 5950
F 0 "U3" H 4968 6567 50 0000 C CNN
F 1 "TPS62162-QFN8-EP / 3V3 BUCK" H 4968 6476 50 0000 C CNN
	1    5050 5950
	-1   0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x08 J4
U 1 1 6
P 8200 2600
F 0 "J4" H 8280 2592 50 0000 L CNN
F 1 "M6 CARRIER HOST MX1.25 LOCK 8P" H 8280 2501 50 0000 L CNN
F 2 "Connector_JST:JST_GH_SM08B-GHS-TB_1x08-1MP_P1.25mm_Horizontal" H 8200 2600 50 0001 C CNN
	1    8200 2600
	1    0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x12 J7
U 1 1 7
P 8200 4500
F 0 "J7" H 8280 4492 50 0000 L CNN
F 1 "UI PANEL MX1.25 LOCK 12P" H 8280 4401 50 0000 L CNN
F 2 "Connector_JST:JST_GH_SM12B-GHS-TB_1x12-1MP_P1.25mm_Horizontal" H 8200 4500 50 0001 C CNN
	1    8200 4500
	1    0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x02 J8
U 1 1 8
P 8200 1700
F 0 "J8" H 8280 1692 50 0000 L CNN
F 1 "M6 SENSOR RAIL MX1.25 2P" H 8280 1601 50 0000 L CNN
F 2 "Connector_JST:JST_GH_SM02B-GHS-TB_1x02-1MP_P1.25mm_Horizontal" H 8200 1700 50 0001 C CNN
	1    8200 1700
	1    0    0    -1
$EndComp
$Comp
L Connector_Generic:Conn_01x04 J5
U 1 1 9
P 8200 6100
F 0 "J5" H 8280 6092 50 0000 L CNN
F 1 "PVDF ADC AUX MX1.25 4P" H 8280 6001 50 0000 L CNN
F 2 "Connector_JST:JST_GH_SM04B-GHS-TB_1x04-1MP_P1.25mm_Horizontal" H 8200 6100 50 0001 C CNN
	1    8200 6100
	1    0    0    -1
$EndComp
$Comp
L Switch:SW_Push SW1
U 1 1 10
P 1900 5900
F 0 "SW1" H 1900 6185 50 0000 C CNN
F 1 "IP5305 POWER KEY" H 1900 6094 50 0000 C CNN
	1    1900 5900
	1    0    0    -1
$EndComp
Text Notes 1150 1200 0    100  ~ 20
USB-C input / CC pull-downs / ESD and PTC are on the mother board
Text Notes 2700 1200 0    100  ~ 20
ESP32-S3 signal budget: M6 SPI + IRQ, UI I2C/I2S/buttons/LEDs, PVDF ADC
Text Notes 7600 1200 0    100  ~ 20
All field harnesses are lockable plug-in or screw/crimp terminated
Text Notes 1250 6650 0    80   ~ 12
BAT_P -> IP5305 5V boost -> SYS_5V -> TPS62162 -> 3V3. SENSOR_RAIL stays external 10-30V.
Text Notes 1250 6850 0    70   ~ 0
The PCB and mechanical board models are generated by generate_board.py; this schematic is the human-readable electrical contract.
Text Notes 1250 7050 0    70   ~ 0
All board-side field connectors are MX1.25 / 1.25 mm; the native .kicad_sch is the current schematic source.
Wire Wire Line
	2300 2250 3000 2250
Text Label 2400 2250 0    50   ~ 0
USB_VBUS
Wire Wire Line
	2300 2350 3000 2350
Text Label 2400 2350 0    50   ~ 0
USB_D+
Wire Wire Line
	2300 2450 3000 2450
Text Label 2400 2450 0    50   ~ 0
USB_D-
Wire Wire Line
	2300 2550 3000 2550
Text Label 2400 2550 0    50   ~ 0
GND
Wire Wire Line
	1850 4550 1850 4350
Text Label 1850 4350 1    50   ~ 0
BAT_P
Wire Wire Line
	1850 4950 1850 5150
Text Label 1850 5150 3    50   ~ 0
GND
Wire Wire Line
	2700 4750 2500 4750
Text Label 2500 4750 2    50   ~ 0
BAT_P
Wire Wire Line
	2700 4850 2500 4850
Text Label 2500 4850 2    50   ~ 0
GND
Wire Wire Line
	2100 5900 2600 5900
Text Label 2200 5900 0    50   ~ 0
POWER_KEY
Wire Wire Line
	1700 5900 1500 5900
Text Label 1500 5900 2    50   ~ 0
GND
Wire Wire Line
	7750 2600 7400 2600
Text Label 7400 2600 2    50   ~ 0
3V3
Wire Wire Line
	7750 2700 7400 2700
Text Label 7400 2700 2    50   ~ 0
GND
Wire Wire Line
	7750 2800 7400 2800
Text Label 7400 2800 2    50   ~ 0
CARRIER_SCK
Wire Wire Line
	7750 2900 7400 2900
Text Label 7400 2900 2    50   ~ 0
CARRIER_MOSI
Wire Wire Line
	7750 3000 7400 3000
Text Label 7400 3000 2    50   ~ 0
CARRIER_MISO
Wire Wire Line
	7750 3100 7400 3100
Text Label 7400 3100 2    50   ~ 0
CARRIER_CS_N
Wire Wire Line
	7750 3200 7400 3200
Text Label 7400 3200 2    50   ~ 0
CARRIER_IRQ_N
Wire Wire Line
	7750 3300 7400 3300
Text Label 7400 3300 2    50   ~ 0
CARRIER_RESET_N
Wire Wire Line
	7750 1700 7400 1700
Text Label 7400 1700 2    50   ~ 0
SENSOR_FUSED
Wire Wire Line
	7750 1800 7400 1800
Text Label 7400 1800 2    50   ~ 0
GND
Wire Wire Line
	8000 2100 7600 2100
Text Label 7600 2100 2    50   ~ 0
SENSOR_EXT_10-30V
Wire Wire Line
	8000 2200 7600 2200
Text Label 7600 2200 2    50   ~ 0
GND
Wire Wire Line
	7750 4500 7400 4500
Text Label 7400 4500 2    50   ~ 0
3V3
Wire Wire Line
	7750 4600 7400 4600
Text Label 7400 4600 2    50   ~ 0
GND
Wire Wire Line
	7750 4700 7400 4700
Text Label 7400 4700 2    50   ~ 0
UI_SDA
Wire Wire Line
	7750 4800 7400 4800
Text Label 7400 4800 2    50   ~ 0
UI_SCL
Wire Wire Line
	7750 4900 7400 4900
Text Label 7400 4900 2    50   ~ 0
UI_BTN_START
Wire Wire Line
	7750 5000 7400 5000
Text Label 7400 5000 2    50   ~ 0
UI_BTN_MODE
Wire Wire Line
	7750 5100 7400 5100
Text Label 7400 5100 2    50   ~ 0
UI_BUZZER
Wire Wire Line
	7750 5200 7400 5200
Text Label 7400 5200 2    50   ~ 0
UI_SPK_BCLK
Wire Wire Line
	7750 5300 7400 5300
Text Label 7400 5300 2    50   ~ 0
UI_SPK_WS
Wire Wire Line
	7750 5400 7400 5400
Text Label 7400 5400 2    50   ~ 0
UI_SPK_DOUT
Wire Wire Line
	7750 5500 7400 5500
Text Label 7400 5500 2    50   ~ 0
UI_LED_STATUS
Wire Wire Line
	7750 5600 7400 5600
Text Label 7400 5600 2    50   ~ 0
UI_LED_BATTERY
Wire Wire Line
	7750 6100 7400 6100
Text Label 7400 6100 2    50   ~ 0
PVDF_ADC_L
Wire Wire Line
	7750 6200 7400 6200
Text Label 7400 6200 2    50   ~ 0
GND
Wire Wire Line
	7750 6300 7400 6300
Text Label 7400 6300 2    50   ~ 0
PVDF_ADC_R
Wire Wire Line
	7750 6400 7400 6400
Text Label 7400 6400 2    50   ~ 0
GND
Wire Wire Line
	8000 6900 7600 6900
Text Label 7600 6900 2    50   ~ 0
PVDF_CMP_AUX_L
Wire Wire Line
	8000 7000 7600 7000
Text Label 7600 7000 2    50   ~ 0
PVDF_CMP_AUX_R
$EndSCHEMATC
